os: windows
language: c
# Install python 3.10.11
before_install:
  - choco install python --version 3.10.11

  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py # Install pip 
  - py -3.10 -m ensurepip                                       # Install pip
  - py -3.10 -m pip install --upgrade pip
  - py -3.10 -m pip install picomc zipfile requests pyinstaller

# Use pyinstaller to build the executable
script:
  - pyinstaller --onefile ----windowed  --name=oneclick-launcher ./Client/main.py