os: windows
language: c
# Install python 3.10.11
before_install:
  - choco install python --version 3.10.11
  - python -m ensurepip --upgrade
  - python -m pip install --upgrade pip
  - python -m pip install picomc zipfile requests pyinstaller

# Use pyinstaller to build the executable
script:
  - pyinstaller --onefile ----windowed  --name=oneclick-launcher ./Client/main.py