os: 
  - linux
  - windows
dist: focal
language: c

branches:
  only:
    - "main"
    - main
    
# Install python3 on windows and linux
before_install:
  - echo $TRAVIS_OS_NAME
  - >-
      case $TRAVIS_OS_NAME in 
        windows)
          rm ~/build -rf
          choco install python --version 3.10.11
          export python="C:\\Python310\\python.exe"
          export pyinstaller="C:\Users\travis\AppData\Roaming\Python\Python310\Scripts\pyinstaller.exe"
          ;;
        linux)
          sudo apt install python3 curl
          export python="python3"
          export python_path = $(which python3)
          export pyinstaller="/home/travis/.local/bin/pyinstaller"
          ;;
      esac

  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

# Install python dependencies
install:
  - $python get-pip.py
  - $python -m pip install --upgrade pip
  - $python -m pip install picomc requests
  - $python -m pip install pyinstaller --user

# Use pyinstaller to build the executable
script:
  - mkdir ~/build
  - $pyinstaller --onefile  --name=oneclick-launcher ./Client/main.py --distpath=~/build
  - ls ~/build

# Setup the tag for the release
before_script:
  # Set up git user name and tag this commit
  - git config --local user.name "ESHARK22"
  - git config --local user.email "admin@eshark.tk"
  - git tag "#$TRAVIS_BUILD_NUMBER"
  - git tag | grep "#"

#Cache the ~/build directory
cache:
  directories:
    - ~/build



deploy:
  # Release to github on final build
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file:
      - ~/build/*
    draft: false
    on:
      condition: $TRAVIS_OS_NAME = windows
      branch:
        - main
        - "main"
    token:
      secure: qITruDqI7xeGFjzsUoe3avEYKACfrE5awqK5+DA+kpOy2XrqsiG87X0on/0PxT5Wx7Jvt0BIljFrEL7Tx/ewS1100SO6dou2y36sdsCExkVwymODGyhUHrOTU8SCV6zwWMYJO3Cil2KDerwld4RBtNUKqHlWurJyMIeca5+8Y19wdpS4tHGRTVI29vyyc7iA0Jca7LfPQXBBW9JYwRZIkhsUfpgBcEsqeCcoMXUCVq9xcMmHaQOnJF03ebstlZqejEHCgUV+m0s6YOMMkmWxer8OeMnUD1mDT/crK4bNNzQ1qNpF43panic1gSfjbqIAxE8PRs83u4YbgoAtHr2buTrpRD0hwujQUT7pCyCjDWYlkoDVBROznwveZUIdHWHnI3wPyvjXaK8xojJz4AVHw1qSWhzPsdoFDb4A4iD2rd2gNNJZOU6TjjnXXKxTk9T+jV+foSD0x9rj3a0XhZZjhtp9p+SBbhGX3e6E/xSQzwyQgER+fKQ3ltKQIJF4pQe/KrkcJ4qE54pSi5J5MlDSrpK1yXU8k7zkhJ1qOdUu3YYwg7iAhrXJFL0DAWFY9HvTHO/tHuBIWU0jNuTPj2bIOATxEMurKLIn0NlrA6ovPgqSqXntcS//bY61EB6fxXIwuF6c3D8Im5VP5afj/Q7xO8+cN4BWf2XBif7Ux8LSvEc=



