os: windows
language: c
# Install python 3.10.11
before_install:
  - choco install python --version 3.10.11

  - py -3.10 -m ensurepip                                       # Install pip
  - py -3.10 -m pip install --upgrade pip
  - py -3.10 -m pip install picomc requests pyinstaller

# Use pyinstaller to build the executable
script:
  - pyinstaller --onefile ----windowed  --name=oneclick-launcher ./Client/main.py